### ISSUE TITLE
Method to load all of a songs information given it's id

### ISSUE THREAD

**Issue by kauffecup** [kauffecup/HangsDB#1]
This'll be used for clicking on a song and displaying all relevant info in the UI

**Comment by ghost** [comment]
SAM IGNORE, JUST IMPLEMENTATION DISCUSSION
What do we want to do for
1) Things like arrangement type, where we store an ID that points to a
different table? We don't need all of that info (for something like
arranged semester we'd just want the name field)
2) Many to manys, where we don't know how many there will be, and again
just need a name?

What's simplest in terms of an api is just one function to get everything
out of the arrangement table for an ID, and other functions to get the many
to manys and get names from IDs. I don't think an API should have specific
functions to get everything at once and string it all together nicely,
rather it should have the basic getters and setters for the database fields.

That said, if you think it's right for the API to do grab everything and
put it all together I can do that, it'll be another complicated query that
I'd have to look up/learn how to write, and I'm not sure right now what the
format would be. I would be up to do things this way, if for no other
reason than for the learning experience, but I think it's better for an API
to have separate getters and setters.

**Comment by kauffecup** [comment]
hmm well i do want it to only be one request from the client

i can set it up so that the endpoint will call all the functions and put them in one json object and send that back to the client. that does some easier to maintain than a crazy-ass query like the last one was

**Comment by kauffecup** [comment]
if you think that its also possible to split up the crazy ass one in to multiple smaller ones i can do a similar thing too

**Comment by kauffecup** [comment]
also i think sam only gets notified if he commented on this or owns it or is somehow related to the issue. i get notifications for urrything because its my repo... and i think you also might get notifications because you're a "collaborator"

**Comment by kauffecup** [comment]
just to clarify though, i am super on board with the multiple simpler queries. just lemme know what they are

**Comment by ghost** [comment]
Okay. They're all done I just need to test before I push.

**Comment by ghost** [comment]
Still need to figure out what to do for _id fields in the arrangement table, but for now see above commit message for the relevant functions.
