### ISSUE TITLE
Method for editing a song's information

### ISSUE THREAD

**Issue by kauffecup** [kauffecup/HangsDB#2]
Not too sure what the signature for this is gonna look like or how it'll work

**Comment by ghost** [comment]
Probably send me a connection, arrangement id, list of (fieldname -> value_to_save) pairs, and a callback.

Junction values will need to be deleted/added separate from this function, as we don't edit them, just add/remove links between the arrangement and the hangover tables (for example).

**Comment by kauffecup** [comment]
aw shucks so theres no way my code can be stupid and send all the info as if i was essentially re-adding the song? i'll hafta keep track of what's different and only send those? and instead of a list maybe it can be a json object with the keys being the fieldname and the value being the value_to_save:

```
{
  name: 'Updated Name',
  nickname: 'Updated Nickname'
}
```

and then your code just iterates over the map to build the query?

**Comment by ghost** [comment]
Yeah that works

**Comment by ghost** [comment]
Call setFieldsForId(connection, arrangement_id, object_with_fields_to_change, callback_function)

Note that passing an id in that object will throw an error to the callback (we can't change ids).

**Comment by kauffecup** [comment]
does this work for changing the multi value junction things too?

**Comment by ghost** [comment]
No, I'll add create and delete functions for each junction (addSoloist, removeSoloist, etc).

**Comment by ghost** [comment]
Added the junction add and delete functions
