### ISSUE TITLE
recent edits/additions list

### ISSUE THREAD

**Issue by sambres8** [kauffecup/HangsDB#5]

**Comment by jtothzynga** [comment]
I'm on it, chief.

**Comment by kauffecup** [comment]
:shipit:

**Comment by kauffecup** [comment]
if I reply to this email will it show up on the issues page?

**Comment by kauffecup** [comment]
woahhh

**Comment by sambres8** [comment]
is that a yes?

also i like that jordan replied from his zynga email

**Comment by ghost** [comment]
Oh shit I probably shouldn't do that.
