### ISSUE TITLE
Adding an arrangement with empty "junction fields" creates an empty row and links them

### ISSUE THREAD

**Issue by kauffecup** [kauffecup/HangsDB#6]
Sorry for the terrible description!

I just created a test song with only a name and a nickname, the following "empty rows" were created:
- empty hangover - connected via arrangement_arranger, arrangement_director, and arrangement_soloist
- empty concert - connected via arrangement_concert
- empty semester - connected via arrangement_semester

here's what i mean by empty:
![image](https://cloud.githubusercontent.com/assets/7032816/6736949/93695fce-ce3e-11e4-9e31-8fa09c19ac2f.png)

**Comment by ghost** [comment]
I thought I'd accounted for that, I guess not.

**Comment by kauffecup** [comment]
i left them in the database so you can see what im talkin bouts

**Comment by ghost** [comment]
Just to check, did everything else come as NULL (not 'NULL') in the
non-junction fields?

**Comment by kauffecup** [comment]
yeah and its the cool italicized NULL where the NULL checkbox is checked

**Comment by ghost** [comment]
Fixed 3/20, form now sends empty string instead of array containing empty string, and dbconnection now ignores array entries of empty strings. Double fixed.
