### ISSUE TITLE
Can you join getPage and getForField queries with some stuffs?

### ISSUE THREAD

**Issue by kauffecup** [kauffecup/HangsDB#7]
Requests:
1. Join the results of `getPage` with their respective `artist_id`s
2. Join the result of `getForField` with `artist_id`, and `arrangement_semester_id`

1 would be helpful for loading the initial song list, and 2 would be helpful for rendering the UI for #3

**Comment by ghost** [comment]
For 1) What's the point of giving you all the information about a song in getPage if you're just going to use getForId? Would just having page return the Name and Artist be alright (if I remember correctly that's the important stuff we want to display to the user, maybe year?), so there isn't so much overlap between the two?

For 2) I would PREFER you look those up yourself (I'd still need to provide the functions for those lookups) but I'd be open to discussing adding a join. What info would you want me to join in from the artist/semester tables? For futureproofing's sake I don't want to give you just a name without an ID (in case we want to click on that semester and see everything arranged then, lookups are done by id so you'll need the id). So name and id? For the semester there's also technically season and semester fields but we haven't been filling them out.

The reason I'd rather not do the join is just to have that function reflect what's stored in the database itself. I don't want to, down the line, have one function that gives you exactly in the database and one that gives you all that same stuff but also does lookups for you, and of the two I'd rather have the first

**Comment by kauffecup** [comment]
Yeah for 1 it does make more sense to just give me the id, song name, and artist name

And for 2 just point me to what method I need to call to get the arrangement semester name - I'll already have the artist name by that point (because of 1)

**Comment by kauffecup** [comment]
also i really thought that the i in gotforid was an l. whats a forld? nothing's a forld.

**Comment by ghost** [comment]
Finished. getPage now sends less info, and getArrangedSemesterForId takes an arrangement ID and gives back the Name, Year, and Semester Type Id (1=Fall, 2=Spring) of the semester when it was arranged. We currently don't set the year and type when creating a semester, but I'd like to switch to using those as it may make searching by year easier.
